### ISSUE TITLE
Issues trying to build with flutter_tts and flutter_twitter_login

### ISSUE THREAD

**Issue by MsXam** [dlutton/flutter_tts#46]
## 🐛 Bug Report

When adding flutter_tts and flutter_twitter_login to an objective-c enabled flutter project we get compiler issues.

### Expected behavior
Adding flutter_tts on its own works without issue & there is no need to create a swift enabled project. 

Just need to ensure : 

- use_frameworks!
- specify swift_version = 4
- add a swift file to the project that will also create the bridging header file.

### Reproduction steps
 Follow the steps above to add flutter_tts to your Obj-c flutter project.  Now add flutter_twitter_login (https://pub.dev/packages/flutter_twitter_login) and ensure in your podfile you set podfile:ios, '11'

do a pod deintegrate and then flutter clean, followed by flutter pub get and finally a pod install.
Ensure one of your files (say main) imports from flutter_twitter_login.

This will install the flutter_twitter_login.

### Compiler errors

When you try and run, you will get lots of compiler issues - a snapshot is shown here  - the issue appears to be one of linking whereby the header files are not found.

    

> /Users/xamgea/workspace/_projects/uajsh/ios/Pods/Protobuf/objectivec/google/protobuf/Wrappers.pbobjc.m:17:10: warning: non-portable path to file '<protobuf/Wrappers.pbobjc.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
>      #import <Protobuf/Wrappers.pbobjc.h>
>              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
>              <protobuf/Wrappers.pbobjc.h>
>     1 warning generated.
>     /Users/xamgea/.pub-cache/git/flutter_twitter_login-04b9d63fe6217cebf8c97f0ccf41719d44554c70/ios/Classes/TwitterLoginPlugin.m:2:9: fatal error: 'TwitterKit/TwitterKit.h' file not found
>     #import <TwitterKit/TwitterKit.h>
>             ^~~~~~~~~~~~~~~~~~~~~~~~~
>     1 error generated.
> Could not build the application for the simulator.
> Error launching application on iPhone Xs.
>

**Comment by dlutton** [comment]
@MsXam are you able to build your app successfully with flutter_twitter_login without flutter_tts?

I noticed you have a conversation going [here](https://github.com/roughike/flutter_twitter_login/issues/12) trying to solve the issue with flutter_twitter_login.

Also, have you tried recreating your app with `flutter create -i swift` so you don't have to jump through the work around you mentioned?

**Comment by MsXam** [comment]
@dlutton yes flutter_twitter_login can build successfully when it is independent from flutter_tts. Initially I thought the issue was because of a flutter upgrade to 1.7.8 however, downgrading back to 1.5.4 still shows the error. The problem is having both flutter_tts and flutter_twitter_login working together. Flutter_tts works seamless as a flutter swift based project and with a few tweaks within an Obj-c flutter project. However getting them both working together is the issue. Yes , creating a project with -i swift only works for flutter_tts but does not allow flutter_twitter_login to compile.

**Comment by dlutton** [comment]
I created a new project with flutter create -i swift and included both flutter_tts and flutter_twitter_login and was able to build the project successfully.

**Comment by MsXam** [comment]
For various reasons I cannot move away from an Obj-c flutter project so need to try and get both plugins working in harmony. However - I tried just as a sanity check to create a new swift project with both plugins and was unable to, so intrigued that you managed this.

Can you : 

1) Advise what version of Cocoapods you are using 
2) Share your Podfile
3) Share your pubspec.yaml
4) What version of flutter/dart you are using
5) What version of Xcode you are using
6) What is your minimum deployment target set to 

Thanks

**Comment by dlutton** [comment]
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.1
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-US)

**pod file:**
```
# Uncomment this line to define a global platform for your project
#platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  use_frameworks!

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

**pubspec.yaml**
```
name: tester
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_tts:
  flutter_twitter_login:
    git:
      url: git://github.com/dlutton/flutter_twitter_login

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
